<div class="form-group">
    <label for="with_original_language">Original Movie Language</label>
    <select
        id="with_original_language"
        name="with_original_language"
        class="selectpicker form-control bg-input"
        data-style="btn">
        <option value="">All</option>
        <option value="en" selected>English</option>
        <option value="de">German</option>
        <option value="fr">French</option>
        <option value="es">Spanish; Castilian</option>
        <option value="ja">Japanese</option>
        <option value="pt">Portuguese</option>
        <option value="it">Italian</option>
        <option value="ru">Russian</option>
        <option value="zh">Chinese</option>
        <option value="ko">Korean</option>
        <option value="nl">Dutch; Flemish</option>
        <option value="sv">Swedish</option>
        <option value="hi">Hindi</option>
        <option value="cs">Czech</option>
        <option value="tr">Turkish</option>
        <option value="cn">Cantonese</option>
        <option value="da">Danish</option>
        <option value="ta">Tamil</option>
        <option value="pl">Polish</option>
        <option value="ml">Malayalam</option>
        <option value="ar">Arabic</option>
        <option value="el">Greek</option>
        <option value="id">Indonesian</option>
        <option value="hu">Hungarian</option>
        <option value="tl">Tagalog</option>
        <option value="fi">Finnish</option>
        <option value="fa">Persian</option>
        <option value="no">Norwegian</option>
        <option value="xx">No Language</option>
        <option value="te">Telugu</option>
        <option value="sr">Serbian</option>
        <option value="th">Thai</option>
        <option value="ro">Romanian</option>
        <option value="he">Hebrew</option>
        <option value="hr">Croatian</option>
        <option value="bn">Bengali</option>
        <option value="vi">Vietnamese</option>
        <option value="ms">Malay</option>
        <option value="sl">Slovenian</option>
        <option value="bg">Bulgarian</option>
        <option value="kn">Kannada</option>
        <option value="sk">Slovak</option>
        <option value="et">Estonian</option>
        <option value="uk">Ukrainian</option>
        <option value="lv">Latvian</option>
        <option value="sq">Albanian</option>
        <option value="lt">Lithuanian</option>
        <option value="ur">Urdu</option>
        <option value="ka">Georgian</option>
        <option value="pa">Panjabi; Punjabi</option>
        <option value="mr">Marathi</option>
        <option value="ca">Catalan; Valencian</option>
        <option value="az">Azerbaijani</option>
        <option value="bs">Bosnian</option>
        <option value="is">Icelandic</option>
        <option value="mk">Macedonian</option>
        <option value="af">Afrikaans</option>
        <option value="eu">Basque</option>
        <option value="ab">Abkhazian</option>
        <option value="nb">Bokmål, Norwegian; Norwegian Bokmål</option>
        <option value="hy">Armenian</option>
        <option value="si">Sinhala; Sinhalese</option>
        <option value="ne">Nepali</option>
        <option value="gl">Galician</option>
        <option value="as">Assamese</option>
        <option value="gu">Gujarati</option>
        <option value="ku">Kurdish</option>
        <option value="kk">Kazakh</option>
        <option value="mn">Mongolian</option>
        <option value="zu">Zulu</option>
        <option value="am">Amharic</option>
        <option value="sh">Serbo-Croatian</option>
        <option value="bo">Tibetan</option>
        <option value="sw">Swahili</option>
        <option value="ky">Kirghiz; Kyrgyz</option>
        <option value="my">Burmese</option>
        <option value="km">Central Khmer</option>
        <option value="uz">Uzbek</option>
        <option value="lb">Luxembourgish; Letzeburgesch</option>
        <option value="jv">Javanese</option>
        <option value="be">Belarusian</option>
        <option value="la">Latin</option>
        <option value="ps">Pushto; Pashto</option>
        <option value="se">Northern Sami</option>
        <option value="mt">Maltese</option>
        <option value="gd">Gaelic; Scottish Gaelic</option>
        <option value="ga">Irish</option>
        <option value="lo">Lao</option>
        <option value="wo">Wolof</option>
        <option value="cy">Welsh</option>
        <option value="bm">Bambara</option>
        <option value="ht">Haitian; Haitian Creole</option>
        <option value="tg">Tajik</option>
        <option value="yi">Yiddish</option>
        <option value="fo">Faroese</option>
        <option value="iu">Inuktitut</option>
        <option value="dv">Divehi; Dhivehi; Maldivian</option>
        <option value="dz">Dzongkha</option>
        <option value="or">Oriya</option>
        <option value="hz">Herero</option>
        <option value="qu">Quechua</option>
        <option value="eo">Esperanto</option>
        <option value="nn">Norwegian Nynorsk; Nynorsk, Norwegian</option>
        <option value="mg">Malagasy</option>
        <option value="cr">Cree</option>
        <option value="mo">Moldavian; Moldovan</option>
        <option value="ha">Hausa</option>
        <option value="mi">Maori</option>
        <option value="gn">Guarani</option>
        <option value="so">Somali</option>
        <option value="ak">Akan</option>
        <option value="tk">Turkmen</option>
        <option value="sm">Samoan</option>
        <option value="mh">Marshallese</option>
        <option value="ln">Lingala</option>
        <option value="xh">Xhosa</option>
        <option value="rw">Kinyarwanda</option>
        <option value="sa">Sanskrit</option>
        <option value="ba">Bashkir</option>
        <option value="ce">Chechen</option>
        <option value="ti">Tigrinya</option>
        <option value="ig">Igbo</option>
        <option value="av">Avaric</option>
        <option value="ay">Aymara</option>
        <option value="za">Zhuang; Chuang</option>
        <option value="sn">Shona</option>
        <option value="ks">Kashmiri</option>
        <option value="ie">Interlingue; Occidental</option>
        <option value="fy">Western Frisian</option>
        <option value="yo">Yoruba</option>
        <option value="ug">Uighur; Uyghur</option>
        <option value="oc">Occitan (post 1500)</option>
        <option value="an">Aragonese</option>
        <option value="su">Sundanese</option>
        <option value="ny">Chichewa; Chewa; Nyanja</option>
        <option value="co">Corsican</option>
        <option value="st">Sotho, Southern</option>
        <option value="aa">Afar</option>
        <option value="ff">Fulah</option>
        <option value="kl">Kalaallisut; Greenlandic</option>
        <option value="os">Ossetian; Ossetic</option>
        <option value="ty">Tahitian</option>
        <option value="gv">Manx</option>
        <option value="ch">Chamorro</option>
        <option value="oj">Ojibwa</option>
        <option value="to">Tonga (Tonga Islands)</option>
        <option value="ts">Tsonga</option>
        <option value="kw">Cornish</option>
        <option value="pi">Pali</option>
        <option value="ho">Hiri Motu</option>
        <option value="lg">Ganda</option>
        <option value="ss">Swati</option>
        <option value="sd">Sindhi</option>
        <option value="ik">Inupiaq</option>
        <option value="tt">Tatar</option>
        <option value="ii">Sichuan Yi; Nuosu</option>
        <option value="kg">Kongo</option>
        <option value="sg">Sango</option>
    </select>
    <small id="with_original_language" class="form-text text-muted">Default: English</small>
</div>
